name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Generate bot token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.ALCOHOL_BOT_ID }}
        private_key: ${{ secrets.ALCOHOL_BOT_PEM }}

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        npm install -g @angular/cli
        npm install -g @ionic/cli
        npm install -g firebase-tools
        npm ci
      env:
        CI: true

    - name: Build dashboard
      run: |
        ionic build --prod
      env:
        CI: true

    - name: Deploy dashboard to Firebase
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="./secrets.json"
        echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        firebase deploy -m ${{ github.ref }}
      env:
        CI: true

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: COVID-19 Dashboard Bonfinópolis de Minas ${{ github.ref }}
        draft: false
        prerelease: false
